import "bootstrap/dist/css/bootstrap-grid.min.css";
import "bootstrap/dist/css/bootstrap-utilities.min.css";
import type { Metadata } from "next";
import GlobalLayout from "../components/GlobalLayout";

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body>
        <GlobalLayout children={children} />
      </body>
    </html>
  );
};

export default RootLayout;
